version: '3.1'

services:
  db:
    container_name: catbotdb
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catbot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  bot:
    build: .
    restart: always
    env_file:
      - catbot.env
    depends_on:
      - db