version: '3.7'

services:
  db:
    container_name: catbotdb
    image: postgres:alpine
    user: "1000:1000"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "./db/data:/var/lib/postgresql/data"
      - "/etc/passwd:/etc/passwd:ro"
    environment:
      POSTGRES_USER: catbot
      POSTGRES_PASSWORD: catbot
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catbot" ]
      interval: 10s
      timeout: 5s
      retries: 5
  bot:
    image: raqbit/catbot
    build: .
    restart: always
    env_file:
      - catbot.env
    depends_on:
      - db
