// Code generated by SQLBoiler 4.3.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CatActivities string
	CatTypes      string
	Cats          string
	Users         string
}{
	CatActivities: "cat_activities",
	CatTypes:      "cat_types",
	Cats:          "cats",
	Users:         "users",
}
